name: sds
channels:
  - conda-forge
dependencies:
  - python=3.10
  - rdkit=2022.09.5
  - pip
  - pip:
      - streamlit==1.32.2
      - PubChemPy==1.0.4
      - pandas==2.2.2
      - python-docx==1.2.0
      - reportlab==4.4.3
